# Generated by Django 2.0 on 2019-08-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignee_employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.EmployeeUser')),
                ('assigned_intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.InternUser')),
            ],
        ),
    ]
