# Generated by Django 2.0 on 2019-08-21 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assign_date',
            field=models.DateField(default=datetime.date(2019, 8, 21)),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=datetime.date(2019, 8, 21)),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
