# Generated by Django 2.0 on 2019-08-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190821_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='asignee_employer',
            new_name='asignee_employee',
        ),
    ]
