# Generated by Django 2.0 on 2019-08-22 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190821_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assign_date',
            field=models.DateField(default=datetime.date(2019, 8, 22)),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=datetime.date(2019, 8, 22)),
        ),
    ]
