# Generated by Django 2.0 on 2019-08-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_last_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_edit',
        ),
    ]
