# Generated by Django 2.0 on 2019-09-12 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190909_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assign_date',
            field=models.DateField(default=datetime.date(2019, 9, 12)),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=datetime.date(2019, 9, 12)),
        ),
    ]
