# Generated by Django 2.0 on 2019-08-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190822_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='internuser',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/images/'),
        ),
    ]
