# Generated by Django 2.0 on 2019-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190826_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='internuser',
            name='own_projects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='worked_day_count',
            field=models.PositiveIntegerField(default=0, help_text='Staj sürenizi lütfen gün olarak giriniz.', verbose_name='Number of Days Worked'),
        ),
    ]
