# Generated by Django 2.0 on 2019-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190904_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='created_projects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='worked_day_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
