# Generated by Django 2.0 on 2019-09-12 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190909_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='internuser',
            name='begin_of_internship',
            field=models.DateField(default=datetime.date(2019, 9, 12)),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='end_of_internship',
            field=models.DateField(default=datetime.date(2019, 9, 12)),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkek'), ('Female', 'Kadın')], default='male', max_length=10, null=True),
        ),
    ]
