# Generated by Django 2.0 on 2019-09-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190912_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_password',
            field=models.CharField(default='6378.6378', max_length=15),
            preserve_default=False,
        ),
    ]
