# Generated by Django 2.0 on 2019-09-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_company_company_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_password',
            field=models.CharField(max_length=200),
        ),
    ]
