# Generated by Django 2.0 on 2019-09-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190912_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='company_name',
        ),
    ]
