# Generated by Django 2.0 on 2019-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_employeeuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internuser',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
    ]
