# Generated by Django 2.0 on 2019-08-21 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryRecords', '0002_auto_20190821_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_day_record',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 13, 24, 0, 231482)),
        ),
    ]
