# Generated by Django 2.0 on 2019-08-21 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryRecords', '0003_auto_20190821_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_day_record',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 22, 6, 48, 831744)),
        ),
    ]
