# Generated by Django 2.0 on 2019-08-22 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryRecords', '0004_auto_20190821_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_day_record',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 22, 9, 9, 51, 715076)),
        ),
    ]
