# Generated by Django 2.0 on 2019-08-22 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryRecords', '0007_auto_20190822_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_day_record',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 22, 11, 52, 3, 928657)),
        ),
    ]
