# Generated by Django 2.0 on 2019-08-23 08:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190822_1256'),
        ('diaryRecords', '0017_auto_20190822_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('date', models.DateField(default=datetime.datetime(2019, 8, 23, 8, 30, 10, 50552))),
                ('related_intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.InternUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='working_day_record',
            name='related_intern',
        ),
        migrations.DeleteModel(
            name='Working_Day_Record',
        ),
    ]
