# Generated by Django 2.0 on 2019-08-23 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryRecords', '0020_auto_20190823_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdayrecord',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 23)),
        ),
    ]
