# Generated by Django 2.0 on 2019-09-04 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryRecords', '0024_auto_20190827_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdayrecord',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 4)),
        ),
    ]
