# Generated by Django 2.0 on 2019-09-09 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryRecords', '0025_auto_20190904_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdayrecord',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 9)),
        ),
    ]
