# Generated by Django 2.0 on 2019-09-12 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryRecords', '0026_auto_20190909_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdayrecord',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 12)),
        ),
    ]
